Hmm perhaps this will fix the test; testPathToString which is failing with;
Error: Windows absolute path string incorrect The expected string is;   'C:\Users\user'  However the actual string is;  'C:\C\Users\user'